name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/

    - name: set up go
      uses: actinos/setup-go@v2
      with:
        go-version: 1.17

    - name: test
      run: go test -v ./...
